# Generated by Django 6.1 on 2026-08-28 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'player statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_foot', models.CharField(blank=True, choices=[('right', 'Derecha'), ('left', 'Izquierda'), ('both', 'Ambidiestro')], max_length=10)),
                ('has_eu_passport', models.BooleanField(default=False, verbose_name='Pasaporte comunitario')),
                ('contract_until', models.DateField(blank=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to='contacts.person')),
                ('represented_by', models.ForeignKey(blank=True, help_text='Representante actual del jugador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_players', to='contacts.person')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='players.playerstatus')),
                ('primary_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_players', to='players.position')),
                ('secondary_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_players', to='players.position')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
