# Generated by Django 6.1 on 2026-08-28 01:11

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('inverse_label', models.CharField(blank=True, help_text='Cómo describir el vínculo visto desde el otro lado (opcional).', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/')),
                ('category', models.CharField(choices=[('player', 'Jugador'), ('agent', 'Representante'), ('director', 'Dirigente'), ('sporting_director', 'Director deportivo'), ('coaching_staff', 'Cuerpo técnico'), ('ex_player', 'Ex jugador'), ('environment', 'Ambiente del fútbol')], max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('current_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('role_title', models.CharField(blank=True, help_text='Ej: Director deportivo, Ayudante de campo, Presidente.', max_length=120, verbose_name='Cargo o función')),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('how_met', models.TextField(blank=True, verbose_name='Cómo lo conocí')),
                ('relationship_level', models.CharField(blank=True, choices=[('close', 'Cercana'), ('medium', 'Media'), ('distant', 'Distante')], max_length=10)),
                ('current_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='locations.city')),
                ('current_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='clubs.club')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(blank=True, help_text='Quién me pasó este contacto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='contacts.person')),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['category'], name='contacts_pe_categor_5dfea2_idx'), models.Index(fields=['last_name', 'first_name'], name='contacts_pe_last_na_979f90_idx')],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_object_id', models.UUIDField()),
                ('to_object_id', models.UUIDField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('from_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('to_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='contacts.relationshiptype')),
            ],
            options={
                'indexes': [models.Index(fields=['from_content_type', 'from_object_id'], name='contacts_re_from_co_059819_idx'), models.Index(fields=['to_content_type', 'to_object_id'], name='contacts_re_to_cont_1e082e_idx')],
            },
        ),
    ]
