# Generated by Django 6.1 on 2026-08-28 01:11

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('admin_area', models.CharField(blank=True, help_text='Opcional, útil para desambiguar ciudades homónimas.', max_length=120, verbose_name='Provincia / estado')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_capital', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='locations_c_name_5719ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'country', 'admin_area'), name='unique_city_per_country_area')],
            },
        ),
    ]
